name: 🐛 Bug Report
description: Report a bug or issue you've found
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this bug! 🙏

        **Just 2 simple steps:**
        1. Describe what's wrong
        2. Tell us how to reproduce it

        That's it! We'll help from there.

  - type: textarea
    id: description
    attributes:
      label: What's the problem?
      description: Describe the bug in your own words
      placeholder: |
        Example: "The login button doesn't work when I click it"

        What you expected: The login form should appear
        What actually happened: Nothing happens when I click
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How can we see this bug?
      description: Tell us the steps to reproduce
      placeholder: |
        1. Go to the login page
        2. Click the "Login" button
        3. See nothing happens
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: Add a screenshot if it helps
      placeholder: Drag and drop an image here

  - type: input
    id: environment
    attributes:
      label: What browser/device? (optional)
      description: Helps us fix faster
      placeholder: "e.g., Chrome on Windows, Safari on iPhone"

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
