blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Mauritania-Programmers-Community/.github/discussions
    about: Ask questions and discuss with the community
  - name: 💼 LinkedIn Community
    url: https://linkedin.com/company/مبرمجي-موريتانيا
    about: Connect with Mauritanian developers
