name: 💡 Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? We'd love to hear it! 💡

        **Just tell us:**
        - What you want
        - Why it would be useful

  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: What feature would you like to see?
      placeholder: |
        Example: "Add a dark mode toggle in the settings"

        Why: Many users prefer dark mode for late-night coding
    validations:
      required: true

  - type: dropdown
    id: willing
    attributes:
      label: Want to help build it?
      description: Contributing is a great way to learn!
      options:
        - "Yes, I can try with help"
        - "Yes, I know how to build this"
        - "No, but I can test it"
        - "Just suggesting the idea"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else? (optional)
      description: Screenshots, examples, or more details
      placeholder: Add images, links, or more details here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Quick check
      options:
        - label: I searched existing issues (no duplicates)
          required: true
        - label: I agree to follow the Code of Conduct
          required: true
