name: ❓ Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Need help? Just ask! 🤝

        **Tip:** Try [Discussions](https://github.com/Mauritania-Programmers-Community/.github/discussions) for general questions - you'll get answers from the whole community!

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What do you need help with?
      placeholder: |
        Example: "How do I push my code to GitHub?"

        What I tried: I ran "git push" but got an error
    validations:
      required: true

  - type: dropdown
    id: level
    attributes:
      label: Your experience level
      description: Helps us give the right answer
      options:
        - Beginner (new to this)
        - Intermediate (some experience)
        - Advanced (experienced)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Quick check
      options:
        - label: I searched for similar questions
          required: true
        - label: I agree to follow the Code of Conduct
          required: true
